import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const globalMenuLinks = [{ link: '/', label: 'Home' }];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = globalMenuLinks.map((link) => {
    return (
      <Link href={link.link} key={link.label}>
        {link.label}
      </Link>
    );
  });

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page">
          <header>
            <div className="links">{links}</div>
            <Link href="/login" className="loginButton">
              Login
            </Link>
          </header>
          <main className="content">{children}</main>
          <footer>TIME-SPACE</footer>
        </div>
      </body>
    </html>
  );
}
